---
- name: Install node_exporter
  hosts: node_exporter
  become: true
  handlers:
    - name: Restart node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted
  pre_tasks:
    - name: Find out what the remote machine's mounts are
      ansible.builtin.slurp:
        src: "{{ hostvars['ca_node']['ca_cert_fullpath'] }}"
      register: ca_cert
      delegate_to: ca_node
  tasks:
    - name: Copy ca cert from control node to the target
      ansible.builtin.copy:
        dest: "/etc/node_exporter/ca-cert.pem"
        content: "{{ ca_cert.content | b64decode }}"
        owner: node-exp
        group: node-exp
        mode: '0644'
      notify: Restart node_exporter
  roles:
    - name: Install and configure node_exporter using the official role
      role: prometheus.prometheus.node_exporter
