---
# handlers file for node_exporter_mtls
- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
- name: Restart snmp_exporter
  ansible.builtin.systemd:
    name: snmp_exporter
    state: restarted
